# Generated by Django 3.2.3 on 2021-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_book_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='tanaka', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='some content'),
        ),
    ]
